import { UserProfile, DailyLog, TodoItem } from "./types";

export const DEFAULT_USER: UserProfile = {
  userId: "shomoy_roy",
  email: "shomoyroy18@gmail.com",
  displayName: "Shomoy Roy",
  currentDay: 16,
  theme: "cyber",
  targetBdtIncome: 100000,
  currentBdtIncome: 45000,
};

export const INITIAL_TODOS: TodoItem[] = [
  // Critical Priorities
  {
    id: "todo-fajr",
    userId: "shomoy_roy",
    taskText: "Fajr Salat in the Mosque (+ Congregational Duas)",
    timeSlot: "04:30",
    priority: "critical",
    completed: true,
    date: "2026-05-31",
  },
  {
    id: "todo-hifz",
    userId: "shomoy_roy",
    taskText: "Quran Hifz: Memorize 3-5 ayahs with deep Tajweed validation",
    timeSlot: "05:00",
    priority: "critical",
    completed: false,
    date: "2026-05-31",
  },
  {
    id: "todo-work1",
    userId: "shomoy_roy",
    taskText: "Deep Work Block 1: Core Systems Engineering (Next-gen compiler setup)",
    timeSlot: "07:00",
    priority: "critical",
    completed: false,
    date: "2026-05-31",
  },
  // High Priorities
  {
    id: "todo-work2",
    userId: "shomoy_roy",
    taskText: "Deep Work Block 2: Freelance Agency & Client Pipeline Pitching",
    timeSlot: "09:30",
    priority: "high",
    completed: false,
    date: "2026-05-31",
  },
  {
    id: "todo-dhuhr",
    userId: "shomoy_roy",
    taskText: "Dhuhr Salat",
    timeSlot: "12:00",
    priority: "high",
    completed: false,
    date: "2026-05-31",
  },
  {
    id: "todo-learn",
    userId: "shomoy_roy",
    taskText: "Python Advanced Track: Concurrent execution and async structures",
    timeSlot: "15:30",
    priority: "high",
    completed: false,
    date: "2026-05-31",
  },
  // Medium/Low
  {
    id: "todo-maghrib",
    userId: "shomoy_roy",
    taskText: "Maghrib Salat & Evening Dhikr with family list",
    timeSlot: "18:30",
    priority: "medium_low",
    completed: false,
    date: "2026-05-31",
  },
  {
    id: "todo-family",
    userId: "shomoy_roy",
    taskText: "Protected Family Connection & Counseling Window",
    timeSlot: "20:00",
    priority: "medium_low",
    completed: false,
    date: "2026-05-31",
  },
  {
    id: "todo-reflection",
    userId: "shomoy_roy",
    taskText: "Evening Reflection & Cognitive Log Transmission to Master Terminal",
    timeSlot: "21:00",
    priority: "medium_low",
    completed: false,
    date: "2026-05-31",
  },
];

// Historical Logs to start with realistic data patterns (pre-populated)
export const INITIAL_LOG_HISTORY: DailyLog[] = [
  {
    id: "log-1",
    userId: "shomoy_roy",
    date: "2026-05-30",
    mood: "good",
    energyLevel: 8,
    salatCongregation: true,
    nicotineFree: true,
    quranHifz: true,
    workoutCompleted: true,
    focusHours: 6.5,
    pipelineLeads: 2,
    notes: "Solid work on freelancing portfolios. Salat list completed perfectly. Energy peaked in work blocks.",
  },
  {
    id: "log-2",
    userId: "shomoy_roy",
    date: "2026-05-29",
    mood: "excellent",
    energyLevel: 9,
    salatCongregation: true,
    nicotineFree: true,
    quranHifz: true,
    workoutCompleted: true,
    focusHours: 8,
    pipelineLeads: 3,
    notes: "Day 30 check completed. High-fidelity systems coding. Memorized 5 ayahs with great recall.",
  },
  {
    id: "log-3",
    userId: "shomoy_roy",
    date: "2026-05-28",
    mood: "average",
    energyLevel: 6,
    salatCongregation: true,
    nicotineFree: true,
    quranHifz: true,
    workoutCompleted: false,
    focusHours: 4.5,
    pipelineLeads: 1,
    notes: "Felt some slight fatigue in afternoon. Managed to resist nicotine cravings through 3-min breathing protocol.",
  },
  {
    id: "log-4",
    userId: "shomoy_roy",
    date: "2026-05-27",
    mood: "good",
    energyLevel: 8,
    salatCongregation: true,
    nicotineFree: true,
    quranHifz: true,
    workoutCompleted: true,
    focusHours: 5.5,
    pipelineLeads: 0,
    notes: "Strong focus hours. Walked 6 miles for workout block. Resumed hifz perfectly.",
  },
  {
    id: "log-5",
    userId: "shomoy_roy",
    date: "2026-05-26",
    mood: "low",
    energyLevel: 5,
    salatCongregation: true,
    nicotineFree: true,
    quranHifz: false,
    workoutCompleted: false,
    focusHours: 3,
    pipelineLeads: 1,
    notes: "A bit of lethargy due to bad sleep cycle. Salat maintained at mosque. Skipped Quran recitation - must compensate.",
  },
];

export const GANTT_PHASES = [
  {
    phase: "Phase 1: Foundation Accelerated",
    days: "Days 1-10",
    dates: "15 June - 24 June",
    tasks: ["▶ Daily Walking Progression", "▶ Bedtime Hardlocked at 22:00", "▶ NRT Patch Deployment", "▶ Physical Inventory Completed"],
    color: "from-orange-500 to-amber-400",
    completed: false,
    current: true,
  },
  {
    phase: "Phase 2: Build & Skill Velocity",
    days: "Days 11-25",
    dates: "25 June - 09 July",
    tasks: ["▶ Strength Training 3x/Wk", "▶ Multiple 90-Min Focus Blocks", "▶ Portfolio Infrastructure Launch", "🚩 MILESTONE 1: Day 25 'নতুন ভোর' (New Dawn)"],
    color: "from-purple-500 to-indigo-500",
    completed: false,
  },
  {
    phase: "Phase 3: Deep Market Execution",
    days: "Days 26-40",
    dates: "10 July - 24 July",
    tasks: ["▰ High-Volume Workouts active", "▰ Client Lead Proposal Pipelines", "🚩 MILESTONE 2: Day 40 'নির্মাণ' (Construction)"],
    color: "from-blue-500 to-cyan-400",
    completed: false,
  },
  {
    phase: "Phase 4: Scale & Takeoff Boost",
    days: "Days 41-50",
    dates: "25 July - 03 August",
    tasks: ["▰ Streamlined Wealth Integration", "▰ Finalize Hifz Module Quran block", "🚩 MILESTONE 3: Day 50 'উড়ান' (Takeoff)"],
    color: "from-emerald-500 to-teal-400",
    completed: false,
  },
  {
    phase: "Phase 5: Resiliency & Failure Insurance Pool",
    days: "Days 51-60",
    dates: "04 August - 13 August",
    tasks: ["▰ 10-Day Built-in Insurance Time Buffer", "▰ Dynamic Failure Compensation protocols", "🚩 FINAL OUTCOME SECURITY LOCK: 1 Lakh BDT Secured"],
    color: "from-pink-500 to-red-500",
    completed: false,
  }
];

export const RELAPSE_MITIGATION_PROTOCOLS = [
  {
    trigger: "ADHD / Task Paralysis Loop",
    vibe: "Severe hyperfocus lock or panic paralysis.",
    mitigation: "Deploy the immediate 2-Minute physical initiation rule. Close all tabs, drop for 10 pushups, and write a single terminal sentence to break the freeze lock.",
  },
  {
    trigger: "Nicotine / Vape Cravings",
    vibe: "Sudden urgent impulse trigger in high pressure states.",
    mitigation: "Bypass decisions. Engage 5-minute deep box breathing sequence. Drink one complete glass of cold water. Send verification witness log to partner or spouse immediately.",
  },
  {
    trigger: "Spiritual Letdown / Congession",
    vibe: "Missing salat congregation or stagnation in Quran Hifz.",
    mitigation: "Bypass emotional analysis. Walk to the nearest mosque instantly. Sit with Quran in hand for 10 minutes without phone access. Re-register and overwrite guilt with immediate physical action.",
  },
  {
    trigger: "Financial Stagnation Cravings",
    vibe: "No responses on pitches or zero leads movement.",
    mitigation: "Commit to making 5 direct lead outreaches (Email, LinkedIn, Upwork) within the next 45 minutes. Action cure-all.",
  }
];
